### ISSUE TITLE
Craft 4: Upgrade/Compatibility

### ISSUE THREAD

**Issue by robzor** [webdna/commerce-bulk-pricing#14]
Hi there,

Firstly, thank you for the great plugin.

Secondly, Craft have now released a Craft 4 upgrade utility (in the CMS Utilities menu) and won't let me upgrade to Craft 4 until your plugin has been updated to be compatible.

It would be amazing if you could update your plugin for Craft 4, thank you!

**Comment by terryupton** [comment]
Yeah, this I would like to echo this too. Are there plans to do this?

**Comment by mcjackson18** [comment]
Hi @robzor, yes we're planning on updating the plugin. We're aiming to have this done next month.

**Comment by robzor** [comment]
Hi @mcjackson18 thank you so much for getting back to me, you're really saving our bacon! :)
